### ISSUE TITLE
In-domain Feedback

### ISSUE THREAD

**Issue by theorist17** [convei-lab/ParlAI#3]
**Is your feature request related to a problem? Please describe.**
Contextual alignment를 초기일회성으로 쓰는 것이 이상해.
결국 expert에 정보를 더 주는 거 아닐까?

**Describe the solution you'd like**
Dynamic contextual feedback으로 missing expertise를 찾아서 expert의 prompt를 data-level augmentataion 하자.
자세히는 fact cross-checking에서 경쟁에서 도태된 epxert를 잘 도와줘서 task-shifting을 유도하자.

**Describe alternatives you've considered**
Response selection 부분에서 expert 모델이 어려워하는 response sample을 찾아 context에 additional annotation하는 게 좋을 것 같아.

**Additional context**
이를 위해선 document retrieval이 1) fined-grained 2) dyanmic 지원이 되어야해.
이렇게 해서 듀얼 태스크 구조로 가는 data-centric approach를 고려하고 있어.

**Comment by min942773** [comment]
결국 데이터셋을 만들 때 대화를 진행하면서 그에 관한 context을 추가로 제공해주자는 이야기인거야? missing expertise = skill description 인거야??

**Comment by theorist17** [comment]
비슷하지.
